Repository TUM-Dev/Campus-Backend, pull requests merged in 2023-03, with the labels that each got.

#100 Feature/iOS Push Notification Service
  .env
  .gitignore
  client/go.mod
  client/go.sum
  client/localServer/localTestClient.go
  docker-compose.yaml
  server/api/CampusService.pb.go
  server/api/CampusService.pb.gw.go
  server/api/CampusService.proto
  server/api/CampusService_grpc.pb.go
  server/api/gen/openapiv2/CampusService.swagger.json
  server/backend/campus_api/campusApi.go
  server/backend/cron/cronjobs.go
  server/backend/cron/iosNotifications.go
  server/backend/device.go
  server/backend/influx/influxClient.go
  server/backend/influx/iosLogging.go
  server/backend/iosNotifications.go
  server/backend/ios_notifications/interfaces.go
  server/backend/ios_notifications/ios_apns/iosAPNsRepository.go
  server/backend/ios_notifications/ios_apns/iosAPNsService.go
  server/backend/ios_notifications/ios_apns/ios_apns_jwt/iosAPNsToken.go
  server/backend/ios_notifications/ios_crypto/encryptedString.go
  server/backend/ios_notifications/ios_device/iosDeviceRepository.go
  server/backend/ios_notifications/ios_device/iosDeviceService.go
  server/backend/ios_notifications/ios_devices_activity_reset/iosDevicesActivityResetRepository.go
  server/backend/ios_notifications/ios_devices_activity_reset/iosDevicesActivityResetService.go
  server/backend/ios_notifications/ios_request_response/iosRequestResponseRepository.go
  server/backend/ios_notifications/ios_request_response/iosRequestResponseService.go
  server/backend/ios_notifications/ios_scheduled_update_log/iosScheduledUpdateLogRepository.go
  server/backend/ios_notifications/ios_scheduling/iosSchedulingRepository.go
  server/backend/ios_notifications/ios_scheduling/iosSchedulingService.go
  server/backend/migration/20221119131300.go
  server/backend/migration/20221210000000.go
  server/backend/migration/migration.go
  server/backend/migration/static_data/iosInitialSchedulingPriorities.json
  server/backend/rpcserver.go
  server/backend/validators.go
  server/model/crontab.go
  server/model/iosDevice.go
  server/model/iosDeviceLastUpdated.go
  server/model/iosDeviceRequestLog.go
  server/model/iosDevicesActivityReset.go
  server/model/iosRemoteNotification.go
  server/model/iosScheduledUpdateLog.go
  server/model/iosSchedulingPriority.go
  server/model/ios_grade.go
  server/swagger/swagger.json
Labels: enhancement

#133 Implemented InfluxDB for Logging Purposes
  .env
  .gitignore
  README.md
  client/go.mod
  client/go.sum
  client/localServer/localTestClient.go
  docker-compose.yaml
  server/api/CampusService.pb.go
  server/api/CampusService.pb.gw.go
  server/api/CampusService.proto
  server/api/CampusService_grpc.pb.go
  server/api/gen/openapiv2/CampusService.swagger.json
  server/backend/campus_api/campusApi.go
  server/backend/cron/cronjobs.go
  server/backend/cron/iosNotifications.go
  server/backend/device.go
  server/backend/influx/influxClient.go
  server/backend/influx/iosLogging.go
  server/backend/influxdb.go
  server/backend/iosNotifications.go
  server/backend/ios_notifications/interfaces.go
  server/backend/ios_notifications/ios_apns/iosAPNsRepository.go
  server/backend/ios_notifications/ios_apns/iosAPNsService.go
  server/backend/ios_notifications/ios_apns/ios_apns_jwt/iosAPNsToken.go
  server/backend/ios_notifications/ios_crypto/encryptedString.go
  server/backend/ios_notifications/ios_device/iosDeviceRepository.go
  server/backend/ios_notifications/ios_device/iosDeviceService.go
  server/backend/ios_notifications/ios_devices_activity_reset/iosDevicesActivityResetRepository.go
  server/backend/ios_notifications/ios_devices_activity_reset/iosDevicesActivityResetService.go
  server/backend/ios_notifications/ios_request_response/iosRequestResponseRepository.go
  server/backend/ios_notifications/ios_request_response/iosRequestResponseService.go
  server/backend/ios_notifications/ios_scheduled_update_log/iosScheduledUpdateLogRepository.go
  server/backend/ios_notifications/ios_scheduling/iosSchedulingRepository.go
  server/backend/ios_notifications/ios_scheduling/iosSchedulingService.go
  server/backend/migration/20221119131300.go
  server/backend/migration/20221210000000.go
  server/backend/migration/migration.go
  server/backend/migration/static_data/iosInitialSchedulingPriorities.json
  server/backend/rpcserver.go
  server/backend/validators.go
  server/go.mod
  server/go.sum
  server/main.go
  server/model/crontab.go
  server/model/iosDevice.go
  server/model/iosDeviceLastUpdated.go
  server/model/iosDeviceRequestLog.go
  server/model/iosDevicesActivityReset.go
  server/model/iosRemoteNotification.go
  server/model/iosScheduledUpdateLog.go
  server/model/iosSchedulingPriority.go
  server/model/ios_grade.go
  server/swagger/swagger.json
Labels: enhancement

#127 Implement Docker Compose For Local Development
  .env
  .gitignore
  README.md
  client/go.mod
  client/go.sum
  client/localServer/localTestClient.go
  docker-compose.yaml
  server/api/CampusService.pb.go
  server/api/CampusService.pb.gw.go
  server/api/CampusService.proto
  server/api/CampusService_grpc.pb.go
  server/api/gen/openapiv2/CampusService.swagger.json
  server/backend/campus_api/campusApi.go
  server/backend/cron/cronjobs.go
  server/backend/cron/iosNotifications.go
  server/backend/device.go
  server/backend/influx/influxClient.go
  server/backend/influx/iosLogging.go
  server/backend/influxdb.go
  server/backend/iosNotifications.go
  server/backend/ios_notifications/interfaces.go
  server/backend/ios_notifications/ios_apns/iosAPNsRepository.go
  server/backend/ios_notifications/ios_apns/iosAPNsService.go
  server/backend/ios_notifications/ios_apns/ios_apns_jwt/iosAPNsToken.go
  server/backend/ios_notifications/ios_crypto/encryptedString.go
  server/backend/ios_notifications/ios_device/iosDeviceRepository.go
  server/backend/ios_notifications/ios_device/iosDeviceService.go
  server/backend/ios_notifications/ios_devices_activity_reset/iosDevicesActivityResetRepository.go
  server/backend/ios_notifications/ios_devices_activity_reset/iosDevicesActivityResetService.go
  server/backend/ios_notifications/ios_request_response/iosRequestResponseRepository.go
  server/backend/ios_notifications/ios_request_response/iosRequestResponseService.go
  server/backend/ios_notifications/ios_scheduled_update_log/iosScheduledUpdateLogRepository.go
  server/backend/ios_notifications/ios_scheduling/iosSchedulingRepository.go
  server/backend/ios_notifications/ios_scheduling/iosSchedulingService.go
  server/backend/migration/20221119131300.go
  server/backend/migration/20221210000000.go
  server/backend/migration/migration.go
  server/backend/migration/static_data/iosInitialSchedulingPriorities.json
  server/backend/rpcserver.go
  server/backend/validators.go
  server/go.mod
  server/go.sum
  server/main.go
  server/model/crontab.go
  server/model/iosDevice.go
  server/model/iosDeviceLastUpdated.go
  server/model/iosDeviceRequestLog.go
  server/model/iosDevicesActivityReset.go
  server/model/iosRemoteNotification.go
  server/model/iosScheduledUpdateLog.go
  server/model/iosSchedulingPriority.go
  server/model/ios_grade.go
  server/swagger/swagger.json
  source-schema.sql
Labels: enhancement

#126 Implement Evironment From `.env` File
  .env
  .gitignore
  README.md
  client/go.mod
  client/go.sum
  client/localServer/localTestClient.go
  docker-compose.yaml
  server/api/CampusService.pb.go
  server/api/CampusService.pb.gw.go
  server/api/CampusService.proto
  server/api/CampusService_grpc.pb.go
  server/api/gen/openapiv2/CampusService.swagger.json
  server/backend/campus_api/campusApi.go
  server/backend/cron/cronjobs.go
  server/backend/cron/iosNotifications.go
  server/backend/device.go
  server/backend/influx/influxClient.go
  server/backend/influx/iosLogging.go
  server/backend/influxdb.go
  server/backend/iosNotifications.go
  server/backend/ios_notifications/interfaces.go
  server/backend/ios_notifications/ios_apns/iosAPNsRepository.go
  server/backend/ios_notifications/ios_apns/iosAPNsService.go
  server/backend/ios_notifications/ios_apns/ios_apns_jwt/iosAPNsToken.go
  server/backend/ios_notifications/ios_crypto/encryptedString.go
  server/backend/ios_notifications/ios_device/iosDeviceRepository.go
  server/backend/ios_notifications/ios_device/iosDeviceService.go
  server/backend/ios_notifications/ios_devices_activity_reset/iosDevicesActivityResetRepository.go
  server/backend/ios_notifications/ios_devices_activity_reset/iosDevicesActivityResetService.go
  server/backend/ios_notifications/ios_request_response/iosRequestResponseRepository.go
  server/backend/ios_notifications/ios_request_response/iosRequestResponseService.go
  server/backend/ios_notifications/ios_scheduled_update_log/iosScheduledUpdateLogRepository.go
  server/backend/ios_notifications/ios_scheduling/iosSchedulingRepository.go
  server/backend/ios_notifications/ios_scheduling/iosSchedulingService.go
  server/backend/migration/20221119131300.go
  server/backend/migration/20221210000000.go
  server/backend/migration/migration.go
  server/backend/migration/static_data/iosInitialSchedulingPriorities.json
  server/backend/rpcserver.go
  server/backend/validators.go
  server/env/environment.go
  server/go.mod
  server/go.sum
  server/main.go
  server/model/crontab.go
  server/model/iosDevice.go
  server/model/iosDeviceLastUpdated.go
  server/model/iosDeviceRequestLog.go
  server/model/iosDevicesActivityReset.go
  server/model/iosRemoteNotification.go
  server/model/iosScheduledUpdateLog.go
  server/model/iosSchedulingPriority.go
  server/model/ios_grade.go
  server/swagger/swagger.json
  source-schema.sql
Labels: enhancement, go

#153 Added missing github.com/golang-jwt/jwt
  server/go.mod
  server/go.sum
Labels: bug
